# makeCacheMatrix  creates a special "matrix", which is really a matrix containing a function to set the value of the matrix, 
# to get the value of the matrix, to set the value of the inverse of the matrix, and to get the value of the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setinvert <- function(solve) m <<- solve
        getinvert <- function() m
        list(set = set, get = get,
             setinvert = setinvert,
             getinvert = getinvert)
}

# cacheSolve takes the object generated by the makeCachMatrix function and generates the inverse of the matrix given to the
# makeCachMatrix function. If the inverse of the matrix has already been calculated, then cacheSolve pulls the result from cache instead.
# This saves time and computation resources.

cacheSolve <- function(x, ...) {
        m <- x$getinvert()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinvert(m)
        m
}

# This is an example invertable matrix
#a1 <- c(3, 2, 5)
#a2 <- c(2, 3, 2)
#a3 <- c(5, 2, 4)
#A <- rbind(a1, a2, a3)         
